version: 2

sources:
  - name: staging
    database: zoomcamp2023-377809
    schema: trip_taxi_data

    tables:
      - name: tripdata_partitioned
      - name: tripdata_nonpartitioned

models:
  - name: stg_tripdata
    description: >
      first created table from BQ
      columns:
      - name: PUlocationID
        tests:
          - not_null
            severity:warn
      - name: DOlocationID
        tests:
          - not_null
            severity:warn
    # columns:
    # - name: SR_Flag
    #   tests:
    #     - not_null:
    #         severity: warn